server:
  port: ${PORT:8080}

app:
  node-id: ${NODE_ID:spring-node-default}
  name: "Spring Boot Distributed Application"
  version: "0.1.0"

spring:
  application:
    name: spring-boot-distributed-playground
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
